-- MySQL Script generated by MySQL Workbench
-- Sun Nov  5 20:21:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`LOV_ NUTRIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOV_ NUTRIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TEXTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_ALIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TAB_ALIMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `DESCRICAO` VARCHAR(400) NULL,
  `TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_NUTRIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TAB_NUTRIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QTD` FLOAT NOT NULL,
  `LOV_ NUTRIENTE_ID` INT NOT NULL,
  `TAB_ALIMENTO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `LOV_ NUTRIENTE_ID`, `TAB_ALIMENTO_ID`),
  INDEX `fk_TAB_NUTRIENTE_LOV_ NUTRIENTE_idx` (`LOV_ NUTRIENTE_ID` ASC),
  INDEX `fk_TAB_NUTRIENTE_TAB_ALIMENTO1_idx` (`TAB_ALIMENTO_ID` ASC),
  CONSTRAINT `fk_TAB_NUTRIENTE_LOV_ NUTRIENTE`
    FOREIGN KEY (`LOV_ NUTRIENTE_ID`)
    REFERENCES `mydb`.`LOV_ NUTRIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAB_NUTRIENTE_TAB_ALIMENTO1`
    FOREIGN KEY (`TAB_ALIMENTO_ID`)
    REFERENCES `mydb`.`TAB_ALIMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_PESSOA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TAB_PESSOA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `IDADE` INT NULL,
  `EMAIL` VARCHAR(100) NULL,
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_REFEICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TAB_REFEICAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `TAB_PESSOA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `TAB_PESSOA_ID`),
  INDEX `fk_TAB_REFEICAO_TAB_PESSOA1_idx` (`TAB_PESSOA_ID` ASC),
  CONSTRAINT `fk_TAB_REFEICAO_TAB_PESSOA1`
    FOREIGN KEY (`TAB_PESSOA_ID`)
    REFERENCES `mydb`.`TAB_PESSOA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_ALIMENTO_has_TAB_REFEICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TAB_ALIMENTO_has_TAB_REFEICAO` (
  `TAB_ALIMENTO_ID` INT NOT NULL,
  `TAB_REFEICAO_ID` INT NOT NULL,
  `TAB_REFEICAO_TAB_PESSOA_ID` INT NOT NULL,
  PRIMARY KEY (`TAB_ALIMENTO_ID`, `TAB_REFEICAO_ID`, `TAB_REFEICAO_TAB_PESSOA_ID`),
  INDEX `fk_TAB_ALIMENTO_has_TAB_REFEICAO_TAB_REFEICAO1_idx` (`TAB_REFEICAO_ID` ASC, `TAB_REFEICAO_TAB_PESSOA_ID` ASC),
  INDEX `fk_TAB_ALIMENTO_has_TAB_REFEICAO_TAB_ALIMENTO1_idx` (`TAB_ALIMENTO_ID` ASC),
  CONSTRAINT `fk_TAB_ALIMENTO_has_TAB_REFEICAO_TAB_ALIMENTO1`
    FOREIGN KEY (`TAB_ALIMENTO_ID`)
    REFERENCES `mydb`.`TAB_ALIMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAB_ALIMENTO_has_TAB_REFEICAO_TAB_REFEICAO1`
    FOREIGN KEY (`TAB_REFEICAO_ID` , `TAB_REFEICAO_TAB_PESSOA_ID`)
    REFERENCES `mydb`.`TAB_REFEICAO` (`ID` , `TAB_PESSOA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
