package View;
import Model.SelecionarAlimentos;
import Model.Nutriente;
import java.util.ArrayList;
import Controller.RefeicaoCtrl;
import DAO.AlimentoDAOJDBC;
import Model.Alimento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class TelaMontarRefeicao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMontarRefeição
     */
    public TelaMontarRefeicao() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CampoNomeRefeicao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoPrecoRefeicao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoKcalRefeicao = new javax.swing.JTextField();
        BtnSalvarRefeicao = new javax.swing.JButton();
        BtnCancelarRefeicao = new javax.swing.JButton();
        txIdUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabAlimento = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabNutrientes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Refeição");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Nutrientes :");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Lista de Alimentos :");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        CampoNomeRefeicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Preço:");

        CampoPrecoRefeicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("KCal:");

        CampoKcalRefeicao.setEditable(false);
        CampoKcalRefeicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        BtnSalvarRefeicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnSalvarRefeicao.setForeground(new java.awt.Color(0, 102, 204));
        BtnSalvarRefeicao.setText("Salvar");
        BtnSalvarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarRefeicao(evt);
            }
        });

        BtnCancelarRefeicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnCancelarRefeicao.setForeground(new java.awt.Color(255, 51, 51));
        BtnCancelarRefeicao.setText("Cancelar");
        BtnCancelarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarRefeicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoPrecoRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoNomeRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(CampoKcalRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txIdUsuario)
                        .addGap(91, 91, 91)
                        .addComponent(BtnCancelarRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSalvarRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CampoNomeRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(CampoKcalRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSalvarRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCancelarRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPrecoRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txIdUsuario))
                        .addGap(37, 37, 37))))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setText("Informações da Refeição:");

        tabAlimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Tipo", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabAlimento);
        if (tabAlimento.getColumnModel().getColumnCount() > 0) {
            tabAlimento.getColumnModel().getColumn(0).setMinWidth(0);
            tabAlimento.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabAlimento.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        tabNutrientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabNutrientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarRefeicaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarRefeicaoActionPerformed

    private void btnSalvarRefeicao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarRefeicao
        RefeicaoCtrl rf =  new RefeicaoCtrl();        
        ArrayList<SelecionarAlimentos> listSa = new ArrayList<SelecionarAlimentos>();
        
        for(int i =0; i< tabAlimento.getRowCount(); i++)
        {            
            SelecionarAlimentos sa = new SelecionarAlimentos();
            sa.setAlimentoQtd(
                    Long.parseLong(tabAlimento.getValueAt(i, 0).toString()), 
                    Float.parseFloat(tabAlimento.getValueAt(i, 4).toString())
            );
            listSa.add(sa);            
        }
        
        String nomeRefeicao = CampoNomeRefeicao.getText();
        float precoRefeicao = Float.parseFloat(CampoPrecoRefeicao.getText());
        Long usuarioLogado = Long.parseLong(txIdUsuario.getText());
        try{
            Boolean resultado = rf.salvarRefeicao(nomeRefeicao, precoRefeicao, listSa, usuarioLogado);
            if(resultado){
                JOptionPane.showMessageDialog(null,"Refeição cadastrada com sucesso!\n\n"
                    + "Nome: " + nomeRefeicao + "\n"
                    + "Preço: " + precoRefeicao + "\n");
                this.dispose();
            }else
            {
                JOptionPane.showMessageDialog(null,"Refeição não foi cadastrada!\n\n"
                    + "Essa refeição já existe no nosso banco de dados \n");
            }
        }catch(Exception e){
            System.out.println(" ERRO AO SALVAR REFEICAO :: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnSalvarRefeicao
    // <editor-fold defaultstate="collapsed" desc="MontarRefeicao">
    public void initMontarRefeicao(ArrayList<SelecionarAlimentos> sa, Long idUsuarioLogado)
    {
        txIdUsuario.setVisible(false);
        txIdUsuario.setText(idUsuarioLogado.toString());
        
        RefeicaoCtrl rf =  new RefeicaoCtrl();
        ArrayList<Nutriente> nutrientes = new ArrayList<>();
        //OBTEM OS NUTRIENTES DESSES ALIMENTOS, JÁ CALCULADOS    
        nutrientes = rf.calculoNutrientes(sa);
        //PREENCHER TABELA DE ALIMENTOS
        preencherTableAlimentos(sa);
        //PREENCHER TABELA DE NUTRIENTES
        preencherTableNutrientes(nutrientes);
        
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="setTableAlimentos">
    public void preencherTableAlimentos(ArrayList<SelecionarAlimentos> sa)
    {
        DefaultTableModel modelo = (DefaultTableModel) tabAlimento.getModel();
        AlimentoDAOJDBC alimentoDao = new AlimentoDAOJDBC();
        
         for(SelecionarAlimentos a: sa){            
            Alimento alimento = alimentoDao.buscarAlimentoID(a.getIdAlimento());
             modelo.addRow(new Object[]{
                alimento.getId(),
                alimento.getNome(),
                alimento.getDescricao(),
                alimento.getTipo(),
                a.getQtd()
            });
        }
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="setTableNutrientes">
    public void preencherTableNutrientes(ArrayList<Nutriente> nutrientes)
    {
        DefaultTableModel modelo = (DefaultTableModel) tabNutrientes.getModel();
        
        for(Nutriente n: nutrientes)
        {
            if(n.getTipo().equals("Calorias"))
            {
                CampoKcalRefeicao.setText(Double.toString(n.getQuantidade()));                
            }else
            {
                modelo.addRow(new Object[]{
                    n.getTipo(),
                    n.getQuantidade()
                });
            }
            
        }
    }
    // </editor-fold> 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelarRefeicao;
    private javax.swing.JButton BtnSalvarRefeicao;
    private javax.swing.JTextField CampoKcalRefeicao;
    private javax.swing.JTextField CampoNomeRefeicao;
    private javax.swing.JTextField CampoPrecoRefeicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabAlimento;
    private javax.swing.JTable tabNutrientes;
    public javax.swing.JLabel txIdUsuario;
    // End of variables declaration//GEN-END:variables
}
